//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int CaseNumber { get; set; }
        public string Product { get; set; }
        public string CaseType { get; set; }
        public string Category { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string ResMessage { get; set; }
    }
}
